plugins:
  - /path/to/my/plugin

orchestrations:
  base_setup:
    hostname: [hostname, username]
    region: [timezone, locale]

install:
  - bash_util

bash_util:
    tools:
        - cdargs
        - aliases

kiosk:
  loading_style: "spinner" # Options: black, spinner, text
  loading_text: "System Starting..." # Only used if loading_style is 'text'
