region:
    # timezone: "America/Chicago"  # Timezone, e.g. "America/New_York", "Europe/London", "Asia/Tokyo"
    locale: "en_US.UTF-8"          # Locale, e.g. "en_US.UTF-8", "en_GB.UTF-8", "fr_FR.UTF-8"

partition:
  # 1. Expand the physical .img file by 5GB (Ignored for live SD cards)
  image_expand_mb: 5000

  # 2. Resize an existing partition (usually partition 2 for root)
  resize_partitions:
    - mount: /       # Mount point of the partition to resize (e.g. /, /home, /data)
      size_mb: 2000      # Expand by 2000MB (if omitted/0, fills remaining space)

  # 3. Add new partitions sequentially
  add_partitions:
    - label: home
      size_mb: 2000      # Fixed size
      fs: ext4
      copy_source: /home # This triggers the special handling
    - label: data
      size_mb: 0         # 0 means "use 100% of the remaining free space"
      fs: ext4

serialport:
    #enable_uart: True
    baudrate: 115200
    #bluetooth: False # If True and enable_uart is True, bluetooth will assigned to mini-UART
    # If True, the console will be enabled on the serial port during startup
    #console: False # Uncomment to set explicitly. If omitted and required by an operation, user is prompted.


bash_util:
    apps: # List of extra apps to install
        - pydf
        - avahi-utils
        - tio
        - htop
        - git
        - i2c-tools
        - screen
        - curl
        - wget
        - zip
        - perl
        - rsync
        - arp-scan
        - nmap
        - lsof
        - net-tools
        - dos2unix
    tools:
        - cdargs
        - aliases
        - commander

rtc:
    #device: mcp7941x  # RTC device, e.g. ds1307, ds3231, pcf8523, mcp7941x
    #addr: null        # I2C address for RTC, e.g. 0x68 for ds1307, ds3231; 0x51 for pcf8523; null for mcp7941x
    sdapin: 22          # SDA pin for RTC
    sclpin: 23          # SCL pin for RTC
    #setup_chrony: True  # If True, install and configure chrony for time

# splashscreen:
#     imagefile: /home/foo/splash.png  # Path to the splash screen image file

network:
  ssh:
    enable: True
  wifi:
    enable: True
    wifi_country: US

orchestrations:
  basic_pi:
    hostname: [hostname, password]
    region: [timezone, locale]
